# Generated by Django 5.2 on 2025-05-02 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientanddoctor',
            old_name='Doctor',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='patientanddoctor',
            old_name='Patient',
            new_name='patient',
        ),
    ]
